export interface ReviewItem {
  id: string;
  name: string;
  rating: number;
  date: string;
  tripType?: string;
  travelGroup?: string;
  text: string;
  highlights?: string[];
  ownerResponse?: string;
  avatarText: string;
  locationRating?: number;
  serviceRating?: number;
  roomsRating?: number;
}

export const REAL_REVIEWS: ReviewItem[] = [
  {
    id: "sanjeev-mann",
    name: "Sanjeev Mann",
    rating: 5,
    date: "4 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Family",
    text: "Had a wonderful stay at Alpine Crest Homestay! The rooms were exceptionally clean, spacious, and beautifully designed with wooden interiors that gave a cozy mountain feel. The balcony offered breathtaking valley and sunset views, making mornings and evenings truly memorable. The hosts were very welcoming, helpful, and always available whenever needed. The property is peaceful, away from the crowd, yet conveniently accessible by road. Wi-Fi connectivity was reliable, making it suitable for work-from-home as well. The washrooms were modern and spotless, and the overall cleanliness of the property was excellent. The home-cooked food was fresh and delicious, adding to the homely experience. If you’re looking for a peaceful stay near Kufri with stunning views, comfortable rooms, and genuine hospitality, I highly recommend Alpine Crest Homestay. Looking forward to visiting again!",
    highlights: ["Great view", "Quiet", "Cozy wooden interiors", "Home-cooked food"],
    avatarText: "SM",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "nancy-soni",
    name: "Nancy Soni",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Couple",
    text: "Had a really pleasant stay at Alpine Crest Homestay. The room was clean and comfortable, and the mountain view from the property was beautiful. The location is peaceful and away from the usual crowd, while still being convenient for visiting Kufri and nearby places. The hosts were friendly and helpful throughout our stay. Overall, a nice place for anyone looking for a quiet stay in the mountains. Would definitely consider staying here again.",
    highlights: ["Luxury", "Great view", "Romantic", "Quiet stay"],
    avatarText: "NS",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "shaurya-thakur",
    name: "Shaurya Thakur",
    rating: 5,
    date: "6 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Friends",
    text: "Had a great trip with friends all thanks to sahil verma working there in the home stay who made our stay more great and stressless. Everything was made by him which made it look easy. One of the best views, food, rooms and services in the whole shimla and other extra paid activities are also provided for eg :- trail walks in nearby adventure resort's, zip line, yak riding and all. All thanks to sahil verma 🫶",
    highlights: ["Luxury", "Great view", "Quiet", "Great value", "Helpful host Sahil"],
    ownerResponse: "Thanks ! Means a lot",
    avatarText: "ST",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "sahhil-verma",
    name: "Sahhil Verma",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Business",
    travelGroup: "Solo",
    text: "Stayed for 2 nights and honestly it was a nice experience. The place is away from the main crowd so it feels very peaceful. Room was good, water was hot and the view in the morning was beautiful. Owner was also very cooperative. Would stay here again.",
    highlights: ["Luxury", "Great view", "Quiet", "Hot water"],
    avatarText: "SV",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "mohmad-murtza",
    name: "Mohmad Murtza",
    rating: 5,
    date: "6 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Friends",
    text: "I had a really pleasant stay here, the place is peaceful with beautiful views, and the owner is very nice and welcoming. It felt comfortable and homely throughout.",
    highlights: ["Homely feel", "Beautiful views", "Welcoming host"],
    ownerResponse: "Thanks sir",
    avatarText: "MM",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "neetu-thakur",
    name: "Neetu Thakur",
    rating: 5,
    date: "5 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Family",
    text: "Best homestay in kufri. Stayed there 2 times and rooms and view is awesome with good price must stay here if visiting kufri.",
    highlights: ["Repeat guest", "Awesome view", "Good price"],
    ownerResponse: "Thank you mam for your valuable review and time",
    avatarText: "NT",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "harpreet-kaur",
    name: "Harpreet Kaur",
    rating: 5,
    date: "Recent on Google",
    tripType: "Vacation",
    travelGroup: "Family",
    text: "Our experience was very good and the hosts were very sweet , welcoming and very helpful throughout our stay . Food was also delicious. Highly recommended",
    highlights: ["Delicious food", "Very sweet hosts", "Quiet environment"],
    avatarText: "HK",
    roomsRating: 4,
    serviceRating: 5,
    locationRating: 4,
  },
  {
    id: "vinod-kumar",
    name: "Vinod Kumar विनोद कुमार",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Couple",
    text: "Nice location. Good for peace lovers. Must try their home made tasty food. Thanks to Sahil best host ever.",
    highlights: ["Tasty homemade food", "Best host Sahil", "Peaceful location"],
    avatarText: "VK",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "dj-ravi",
    name: "༆Dj ᭄RAVI༆࿐",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Solo",
    text: "Travelled to this property in monsoon the view is insane and food is best ever tasted. Must try if you wanna stay in a serene location for peace lovers.",
    highlights: ["Insane monsoon view", "Best food ever", "Serene location"],
    avatarText: "DR",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "aryan",
    name: "Aryan",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Friends",
    text: "Had a nice stay at Alpine Crest Homestay. Rooms were clean and comfortable. The view from the property was really good and the place is very peaceful. Host was also helpful. Overall good experience.",
    highlights: ["Clean & comfortable", "Helpful host", "Peaceful"],
    avatarText: "AR",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "navneet-thakur",
    name: "Navneet Thakur",
    rating: 5,
    date: "5 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Family",
    text: "Best homestay in kufri.... 🚩 Rooms are well cleaned and location is very amazing view of mountains 🏔️ ❤️",
    highlights: ["Well cleaned rooms", "Amazing mountain view"],
    ownerResponse: "Thanks sir for your feedback",
    avatarText: "NT",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "manjeet-kumar",
    name: "Manjeet Kumar",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Friends",
    text: "Best property for people chasing peace and home like experience.",
    highlights: ["Peace & quiet", "Home-like experience"],
    avatarText: "MK",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "mohit-sharma",
    name: "Mohit Sharma",
    rating: 5,
    date: "a month ago on Google",
    tripType: "Vacation",
    travelGroup: "Friends",
    text: "Very nice place to stay near kufri.",
    highlights: ["Great stay near Kufri", "Great value"],
    avatarText: "MS",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "arzoo-verma",
    name: "Arzoo Verma",
    rating: 5,
    date: "6 months ago on Google",
    text: "I had an amazing experience. Rooms are well cleaned and property is in very beautiful location.",
    highlights: ["Amazing experience", "Clean rooms", "Beautiful location"],
    ownerResponse: "Thanks mam",
    avatarText: "AV",
  },
  {
    id: "neha-patial",
    name: "NEHA PATIAL",
    rating: 5,
    date: "4 months ago on Google",
    text: "Wonderful service and very comfortable mountain stay.",
    highlights: ["Wonderful service"],
    avatarText: "NP",
    roomsRating: 5,
    serviceRating: 5,
  },
  {
    id: "anu-mittal",
    name: "Anu Mittal",
    rating: 5,
    date: "4 months ago on Google",
    tripType: "Vacation",
    travelGroup: "Family",
    text: "Wonderful place for a family mountain vacation.",
    highlights: ["Wonderful place"],
    avatarText: "AM",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "shivam-bhardwaj",
    name: "Shivam Bhardwaj",
    rating: 5,
    date: "a month ago on Google",
    travelGroup: "Friends",
    text: "Village Vibe 😵💫💨 Amazing home-cooked food ❣️ Great mountain view.",
    highlights: ["Village Vibe", "Delicious food", "Great view"],
    avatarText: "SB",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "nisha-dhindoli",
    name: "Nisha Dhindoli",
    rating: 5,
    date: "4 months ago on Google",
    text: "Clean, comfortable rooms with excellent hospitality and fast service.",
    highlights: ["Clean rooms", "Great service"],
    avatarText: "ND",
    roomsRating: 5,
    serviceRating: 5,
  },
  {
    id: "uma-kanwar",
    name: "Uma Kanwar",
    rating: 5,
    date: "4 months ago on Google",
    text: "Peaceful stay with scenic mountain views and warm hosts.",
    highlights: ["Great view", "Peaceful"],
    avatarText: "UK",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
  {
    id: "yog-raj",
    name: "Yog Raj",
    rating: 5,
    date: "a month ago on Google",
    text: "Good property, clean rooms, hospitable service and great location.",
    highlights: ["Good experience"],
    avatarText: "YR",
    roomsRating: 5,
    serviceRating: 5,
    locationRating: 5,
  },
];
